/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as NewsRouteImport } from './routes/news'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIdRouteImport } from './routes/news.$id'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/news': typeof NewsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/news/$id': typeof NewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/news': typeof NewsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/news/$id': typeof NewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/news': typeof NewsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/news/$id': typeof NewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/documents'
    | '/news'
    | '/resources'
    | '/news/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/documents' | '/news' | '/resources' | '/news/$id'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/documents'
    | '/news'
    | '/resources'
    | '/news/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  NewsRoute: typeof NewsRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
  }
}

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  NewsRoute: NewsRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
